name: Shellcheck

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: json1
          severity: warning
        # uses: reviewdog/action-shellcheck@v1.32.0
        # with:
        #   fail_level: warning
        #   reporter: github-check

      # - name: Convert ShellCheck JSON to SARIF
      #   if: always()
      #   run: |
      #     npx shellcheck-sarif shellcheck.json > shellcheck.sarif

      # - name: Upload SARIF to GitHub Code Scanning
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: shellcheck.sarif
